In [43]:
# Create a string variable
city_name = 'City A'

# Print the value of the string variable
print(f"City: ",city_name)

City:  City A


In [47]:
def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32


celsius = int(input('Enter temp: '))
fahrenheit = celsius_to_fahrenheit(celsius)
print(f"{celsius}°C is equal to {fahrenheit}°F")


Enter temp:  243


243°C is equal to 469.4°F


In [49]:
# Create a float var for carbon footprint
carbon_footprint = 500.75 # Kg CO2
print(f'Carbon footprint: ', carbon_footprint)

Carbon footprint:  500.75


In [51]:
is_sustainable = carbon_footprint < 400

print(f'Is the city sustainable? \nAns: ', is_sustainable)

Is the city sustainable? 
Ans:  False


In [53]:
num = input("Enter a number: ")

try:
    int(num)
    if type(int(num)) is int:
        print(f"{num} is an integer.")
except ValueError:
    print(f"{num} is not an integer.")

Enter a number:  47


47 is an integer.


In [55]:
num = [1,2,3,4,5]

if 1 in num:
    print("1 is in the list!")
else:
    print("1 is not in the list.")


1 is in the list!


In [59]:
## op = input('Choose operation (+, -, *, /): ')
n1 = float(input('Enter num1: '))
n2 = float(input('Enter num2: '))
result = 0
if n2 == 0:
    print('Invalid')
if op == '+':
    result = n1 + n2
elif op == '-':
    result = n1 - n2
elif op == '*':
    result = n1 * n2
elif op == '/':
    result = n1 / n2
else:
    print('Invalid operation')

print(f'Result: ',result)


Choose operation (+, -, *, /):  2+2
Enter num1:  2
Enter num2:  2


Invalid operation
Result:  0


In [61]:
# Sample data set
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]

high_temp_threshold = 26

high_temp_cities = [city for city in climate_data if city['temperature'] > high_temp_threshold]

print('Cities with high temperature (> 26°C):')
for city in high_temp_cities:
    print(f"{city['city']} - {city['temperature']}°C")


Cities with high temperature (> 26°C):
City B - 30°C
City E - 28°C


In [63]:
# Calculate the average carbon footprint
total_carbon_footprint = sum(city["carbon_footprint"] for city in climate_data)
average_carbon_footprint = total_carbon_footprint / len(climate_data)

print(f"Average carbon footprint: {average_carbon_footprint}")


Average carbon footprint: 420.0


In [65]:
# Find the city with the highest carbon footprint
highest_carbon_city = max(climate_data, key=lambda city: city["carbon_footprint"])

print(f"City with the highest carbon footprint: {highest_carbon_city['city']} with {highest_carbon_city['carbon_footprint']} units")


City with the highest carbon footprint: City C with 600 units


In [67]:
#Example usage:
# Function to calculate carbon footprint
def calculate_carbon_footprint(energy_consumption, emission_factor):
    return energy_consumption * emission_factor

# Example usage
energy_consumption = 1000  # in kWh
emission_factor = 0.475  # in kg CO2 per kWh
carbon_footprint = calculate_carbon_footprint(energy_consumption, emission_factor)
print(f"Carbon footprint: {carbon_footprint} kg CO2")



Carbon footprint: 475.0 kg CO2


In [69]:
# Define the sustainability threshold
sustainability_threshold = 400

# Filter the cities based on the carbon footprint
sustainable_cities = [city for city in climate_data if city["carbon_footprint"] < sustainability_threshold]
unsustainable_cities = [city for city in climate_data if city["carbon_footprint"] >= sustainability_threshold]

print("Sustainable cities:")
for city in sustainable_cities:
    print(f"{city['city']} - {city['carbon_footprint']} units")

print("\nUnsustainable cities:")
for city in unsustainable_cities:
    print(f"{city['city']} - {city['carbon_footprint']} units")


Sustainable cities:
City B - 350 units
City D - 200 units

Unsustainable cities:
City A - 500 units
City C - 600 units
City E - 450 units


In [71]:
#leap year
def is_leap_year():
    year = int(input("Enter a year: "))
    if year % 4 != 0:
        print(f"{year} is not a leap year.")
    elif year % 100 != 0:
        print(f"{year} is a leap year.")
    elif year % 400 != 0:
        print(f"{year} is not a leap year.")
    else:
        print(f"{year} is a leap year.")

is_leap_year()

Enter a year:  2008


2008 is a leap year.


In [73]:
def is_leap_year(year: int) -> bool:
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)

In [75]:
import pandas as pd

In [77]:
import pandas as pd

renewable_sources = ['Solor', 'Wind','Hydropower', 'Geothermal', 'Biomass']
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

In [79]:
import pandas as pd
projects_df = pd.DataFrame(data)
selected_rows = projects_df.iloc[[1, 2]]
print(selected_rows)

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022  


In [81]:
info = projects_df.info()
print(info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW)     5 non-null      int64 
 3   Cost (Million $)  5 non-null      int64 
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes
None


In [83]:
describe = projects_df.describe()
print(describe)

       Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000


In [88]:
df = pd.DataFrame(data)
# Check whose capacity is more than 100MW
more_than_100mw = df[df['Capacity (MW)'] > 100]
print("Projects with capacity more than 100MW:")
print(more_than_100mw)

Projects with capacity more than 100MW:
          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [94]:
df = pd.DataFrame(data)
df['Cost per MW ($/MW)'] = df['Cost (Million $)'] / df['Capacity (MW)']
print(df)

              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW ($/MW)  
0  California             2023            1.333333  
1       Texas             2024            1.333333  
2  Washington             2022            1.750000  
3      Nevada             2025            2.000000  
4       Idaho             2023            2.500000  


In [97]:
df = pd.DataFrame(data)

# Aggregate the data to find the total capacity and the total cost
total_capacity = df['Capacity (MW)'].sum()
total_cost = df['Cost (Million $)'].sum()

print("Total Capacity: {:.2f} MW".format(total_capacity))
print("Total Cost: ${:.2f} Million $".format(total_cost))

Total Capacity: 800.00 MW
Total Cost: $1300.00 Million $


In [101]:
df = pd.DataFrame(data)

# Group the data by technology type and calculate the total capacity for each type of technology
GROUPED_DATA = df.groupby('Technology')['Capacity (MW)'].sum()

print("Total Capacity by Technology:")
print(GROUPED_DATA)

Total Capacity by Technology:
Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


In [103]:
#Exploring Numpy for data manipulation

import numpy as np

In [105]:
one_d_array = np.array([1,2,3])
print(one_d_array)

[1 2 3]


In [111]:
two_d_array = np.array([[1,2],[3,4]])
print(two_d_array)

[[1 2]
 [3 4]]


In [121]:
array = np.array([[1,2,5],[3,4,6]])
# Get information about the array
print("Shape:", array.shape)
print("Dimension:", array.ndim)
print("Size:", array.size)
print("Data Type:", array.dtype)
print("Item Size:", array.itemsize)

Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int32
Item Size: 4


In [127]:
import numpy as np

# Create an array of ones
ones_array = np.ones(3)
print("Array of ones:")
print(ones_array)

# Create an array of zeros
zeros_array = np.zeros(3)
print("\nArray of zeros:")
print(zeros_array)

# Create an array of random numbers between 0 and 1
random_array = np.random.random(3)
print("\nArray of random numbers:")
print(random_array)

Array of ones:
[1. 1. 1.]

Array of zeros:
[0. 0. 0.]

Array of random numbers:
[0.25816324 0.34947897 0.5861011 ]


In [131]:
import numpy as np
# Create a 3x3 array filled with the value 10
array = np.full((3, 3), 10)
print(array)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [137]:
import numpy as np
# Create a 3x3 identity matrix
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [139]:
array1 = np.array(0,10,2)
print(array1)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [143]:
import numpy as np
# Create an array of evenly spaced values from 0 to 10
array = np.linspace(5,10,3)
print(array)

[ 5.   7.5 10. ]


In [147]:
import numpy as np

# Create an array of evenly spaced values from 2.0 to 3.0
array = np.linspace(2.0, 3.0, 6, endpoint=True, retstep=True)
print(array)

(array([2. , 2.2, 2.4, 2.6, 2.8, 3. ]), 0.2)


In [149]:
num_data = np.array([11,22,33,44,55,66,77,88,99])
print(num_data[:])

print(num_data[:1])
print(num_data[:2])
print(num_data[:-1])

[11 22 33 44 55 66 77 88 99]
[11]
[11 22]
[11 22 33 44 55 66 77 88]


In [151]:
def is_palindrome(num):
    num_str = str(num)
    for i in range(len(num_str) // 2):
        if num_str[i] != num_str[-i - 1]:
            return False
    return True

# Test the function
num = 12321
print(f"Is {num} a palindrome? {is_palindrome(num)}")

Is 12321 a palindrome? True


In [159]:
def is_palindrome(num):
    num_str = str(num)
    return num_str == num_str[::-1]
# Get the input from the user
while True:
    num = input("Enter a number: ")
    try:
        num = int(num)
        break
    except ValueError:
        print("Invalid input. Please enter a valid integer.")
# Check if the input is a palindrome
if is_palindrome(num):
    print(f"{num} is a palindrome.")
else:
    print(f"{num} is not a palindrome.")

Enter a number:  123321


123321 is a palindrome.


In [167]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr.reshape(1, 9))
print(arr.reshape(3, 3))

[[1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [175]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:")
print(arr)
# Transpose the array using the np.transpose function
transposed_arr = np.transpose(arr)
print("\nTransposed array:")
print(transposed_arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [181]:
import numpy as np
myarray = np.array([[1,2,3],[4,5,6]])
print(myarray.flatten())

[1 2 3 4 5 6]


In [191]:
# Create an array for energy consumption (in kWh)
energy_consumption = np.array([1200, 3400, 2900, 1800, 2500])

# Calculate the mean
mean_consumption = np.mean(energy_consumption)
print("Mean energy consumption (kWh):", mean_consumption)

# Calculate the median
median_consumption = np.median(energy_consumption)
print("Median energy consumption (kWh):", median_consumption)

# Calculate the standard deviation
std_dev_consumption = np.std(energy_consumption)
print("Standard deviation of energy consumption (kWh):", std_dev_consumption)

# Calculate the variance
variance_consumption = np.var(energy_consumption)
print("Variance of energy consumption (kWh):", variance_consumption)

Mean energy consumption (kWh): 2360.0
Median energy consumption (kWh): 2500.0
Standard deviation of energy consumption (kWh): 781.2809993849844
Variance of energy consumption (kWh): 610400.0


In [193]:
print(energy_consumption.reshape(5,1))

[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]
